export const COMMON_WORDS: string[] = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i", "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other", "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way", "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "make", "game", "life", "know", "feel", "home", "play", "show", "love", "work", "keep", "part", "find", "mind", "need", "held", "turn", "face", "case", "area",
  "city", "body", "word", "hand", "read", "book", "side", "line", "head", "form", "land", "seen", "lost", "page", "left", "mile", "feet", "care", "true", "walk",
  "long", "much", "each", "many", "such", "very", "were", "went", "came", "sent", "told", "took", "once", "does", "done", "gave", "find", "kind", "mind", "wind",
  "here", "both", "last", "next", "hard", "easy", "soft", "high", "deep", "wide", "near", "away", "fast", "slow", "loud", "dark", "warm", "cold", "fine", "pure",
  "rich", "poor", "free", "full", "half", "main", "real", "sure", "wise", "wild", "calm", "cool", "open", "shut", "easy", "busy", "glad", "sad", "fair", "dark",
  "blue", "red", "green", "white", "black", "pink", "grey", "gold", "iron", "lead", "wood", "coal", "stone", "sand", "clay", "soil", "dust", "rain", "snow", "wind",
  "about", "above", "across", "act", "actor", "active", "activity", "add", "address", "admit", "adopt", "adult", "advice", "advise", "afford", "afraid", "after", "afternoon", "again", "against",
  "age", "agency", "agent", "ago", "agree", "agreement", "ahead", "air", "alarm", "alive", "allow", "almost", "alone", "along", "already", "also", "although", "always", "among", "amount",
  "analysis", "ancient", "anger", "angle", "angry", "animal", "annual", "another", "answer", "anxiety", "anxious", "anybody", "anymore", "anyone", "anything", "anyway", "anywhere", "apart", "apartment", "appeal",
  "appear", "appearance", "apple", "application", "apply", "appoint", "appointment", "approve", "area", "argue", "argument", "arise", "arm", "army", "around", "arrange", "arrangement", "arrest", "arrival", "arrive",
  "art", "article", "artist", "as", "ash", "aside", "ask", "asleep", "aspect", "assault", "assert", "assess", "assessment", "asset", "assign", "assignment", "assist", "assistance", "assistant", "associate",
  "association", "assume", "assumption", "assure", "at", "athlete", "athletic", "atmosphere", "attach", "attack", "attempt", "attend", "attendance", "attention", "attitude", "attorney", "attract", "attraction", "attractive", "attribute",
  "audience", "author", "authority", "automatic", "automatically", "automobile", "autumn", "available", "average", "avoid", "award", "aware", "awareness", "away", "awful", "baby", "back", "background", "backward", "bacon",
  "bad", "badly", "bag", "bake", "balance", "ball", "balloon", "ban", "band", "bank", "bar", "bare", "barely", "bargain", "bark", "barrel", "barrier", "base", "baseball", "basic",
  "basically", "basis", "basket", "basketball", "bath", "bathroom", "battery", "battle", "bay", "be", "beach", "beam", "bean", "bear", "beard", "beast", "beat", "beautiful", "beauty", "because",
  "become", "bed", "bedroom", "beef", "beer", "before", "beg", "begin", "beginner", "beginning", "behalf", "behave", "behavior", "behind", "being", "belief", "believe", "bell", "belong", "below",
  "belt", "bench", "bend", "beneath", "benefit", "beside", "besides", "best", "bet", "better", "between", "beyond", "bible", "bicycle", "bid", "big", "bike", "bill", "billion", "bind",
  "biology", "bird", "birth", "birthday", "biscuit", "bit", "bite", "bitter", "black", "blade", "blame", "blank", "blanket", "blast", "blend", "bless", "blind", "blink", "block", "blood",
  "bloody", "blow", "blue", "board", "boast", "boat", "body", "boil", "bold", "bolt", "bomb", "bond", "bone", "bonus", "book", "boom", "boot", "booth", "border", "bore",
  "bored", "boring", "born", "borrow", "boss", "both", "bother", "bottle", "bottom", "bounce", "bound", "boundary", "bow", "bowl", "box", "boy", "boyfriend", "brain", "brake", "branch",
  "brand", "brass", "brave", "bread", "break", "breakfast", "breast", "breath", "breathe", "breeze", "brick", "bridge", "brief", "briefly", "bright", "brilliant", "bring", "broad", "broadcast", "broken",
  "bronze", "brother", "brow", "brown", "brush", "bubble", "bucket", "budget", "build", "builder", "building", "bulb", "bulk", "bullet", "bunch", "bundle", "burden", "bureau", "burn", "burst",
  "bury", "bus", "bush", "business", "busy", "but", "butter", "button", "buy", "buyer", "by", "cab", "cabin", "cabinet", "cable", "cake", "calculate", "calculation", "calculator", "calendar",
  "call", "calm", "camera", "camp", "campaign", "campus", "can", "canal", "cancel", "cancer", "candidate", "candle", "candy", "cane", "canvas", "cap", "capability", "capable", "capacity", "cape",
  "capital", "captain", "capture", "car", "carbon", "card", "care", "career", "careful", "carefully", "careless", "cargo", "carpet", "carriage", "carrier", "carrot", "carry", "cart", "carve", "case",
  "cash", "cast", "castle", "casual", "cat", "catalog", "catch", "category", "cathedral", "cattle", "cause", "caution", "cave", "ceiling", "celebrate", "celebration", "celebrity", "cell", "cemetery", "census",
  "cent", "center", "central", "century", "ceremony", "certain", "certainly", "certificate", "chain", "chair", "chairman", "challenge", "chamber", "champion", "championship", "chance", "change", "channel", "chaos", "chapter",
  "character", "characteristic", "charge", "charity", "charm", "chart", "chase", "chat", "cheap", "cheat", "check", "cheek", "cheer", "cheese", "chef", "chemical", "chemistry", "chest", "chew", "chicken",
  "chief", "child", "childhood", "chimney", "chin", "chip", "chocolate", "choice", "choir", "choose", "chop", "chorus", "chronic", "chunk", "church", "cigarette", "cinema", "circle", "circuit", "circulate",
  "circumstance", "citizen", "city", "civil", "civilian", "claim", "clap", "clarify", "clash", "class", "classic", "classical", "classify", "classroom", "claw", "clay", "clean", "cleaner", "clear", "clearly",
  "clerk", "clever", "click", "client", "cliff", "climate", "climb", "clinic", "clip", "clock", "close", "closed", "closely", "closet", "cloth", "clothes", "clothing", "cloud", "cloudy", "club",
  "clue", "cluster", "coach", "coal", "coast", "coat", "code", "coffee", "cognitive", "coin", "cold", "collapse", "collar", "colleague", "collect", "collection", "collective", "collector", "college", "collision",
  "colony", "color", "column", "combat", "combination", "combine", "come", "comedy", "comfort", "comfortable", "command", "commander", "comment", "commerce", "commercial", "commission", "commit", "commitment", "committee", "common",
  "commonly", "communicate", "communication", "community", "companion", "company", "compare", "comparison", "compass", "compel", "compete", "competition", "competitive", "competitor", "complain", "complaint", "complete", "completely", "complex", "complexity",
  "compliance", "complicate", "complicated", "component", "compose", "composer", "composition", "compound", "comprehensive", "compromise", "computer", "conceal", "concede", "concept", "conception", "concern", "concerned", "concert", "conclude", "conclusion",
  "concrete", "condition", "conduct", "conductor", "conference", "confess", "confession", "confidence", "confident", "confirm", "confirmation", "conflict", "confront", "confuse", "confused", "confusion", "congratulate", "congress", "connect", "connection",
  "conscious", "consciousness", "consensus", "consent", "consequence", "consequently", "conservation", "conservative", "consider", "considerable", "considerably", "consideration", "consist", "consistent", "consistently", "console", "constant", "constantly", "constitute", "constitution",
  "constraint", "construct", "construction", "consult", "consultant", "consultation", "consume", "consumer", "consumption", "contact", "contain", "container", "contemporary", "content", "contest", "context", "continent", "continue", "continuous", "contract",
  "contractor", "contradict", "contrary", "contrast", "contribute", "contribution", "contributor", "control", "controversial", "controversy", "convenience", "convenient", "convention", "conventional", "conversation", "conversion", "convert", "convey", "convict", "conviction",
  "convince", "convinced", "cook", "cookie", "cooking", "cool", "cooperate", "cooperation", "coordinate", "cop", "cope", "copper", "copy", "cord", "core", "corn", "corner", "corporate", "corporation", "correct",
  "correction", "correctly", "correlate", "corridor", "corruption", "cost", "costly", "cottage", "cotton", "couch", "cough", "could", "council", "counsel", "counselor", "count", "counter", "counterpart", "country", "countryside",
  "county", "couple", "courage", "course", "court", "cousin", "cover", "coverage", "cow", "cowboy", "crack", "craft", "crash", "crawl", "crazy", "cream", "create", "creation", "creative", "creativity",
  "creator", "creature", "credibility", "credit", "crew", "crime", "criminal", "crisis", "criteria", "critic", "critical", "critically", "criticism", "criticize", "crop", "cross", "crowd", "crowded", "crown", "crucial",
  "crude", "cruel", "cruise", "crush", "cry", "crystal", "cube", "cultivate", "cultural", "culture", "cup", "board", "cure", "curiosity", "curious", "curl", "currency", "current", "currently", "curriculum",
  "curtain", "curve", "cushion", "custody", "custom", "customer", "cut", "cute", "cycle", "cynical", "dad", "daily", "dairy", "dam", "damage", "damp", "dance", "dancer", "danger", "dangerous",
  "dare", "dark", "darkness", "darling", "dash", "data", "database", "date", "daughter", "dawn", "day", "daylight", "dead", "deadline", "deaf", "deal", "dealer", "dear", "death", "debate",
  "debris", "debt", "decade", "decay", "decent", "decide", "decision", "deck", "declare", "decline", "decorate", "decoration", "decrease", "dedicate", "dedication", "deed", "deep", "deeply", "deer", "defeat",
  "defend", "defendant", "defender", "defense", "defensive", "deficit", "define", "definite", "definitely", "definition", "defy", "degree", "delay", "delegate", "delegation", "delete", "deliberate", "deliberately", "delicate", "delicious",
  "delight", "delighted", "deliver", "delivery", "demand", "democracy", "democrat", "democratic", "demolish", "demonstrate", "demonstration", "denial", "denounce", "dense", "density", "dental", "deny", "depart", "departure", "department",
  "depend", "dependence", "dependent", "depict", "deploy", "deployment", "deposit", "depress", "depressed", "depression", "depth", "deputy", "derive", "descend", "descent", "describe", "description", "desert", "deserve", "design",
  "designer", "desirable", "desire", "desk", "despair", "desperate", "desperately", "despite", "destination", "destroy", "destruction", "destructive", "detach", "detail", "detailed", "detain", "detect", "detection", "detective", "determination",
  "determine", "determined", "develop", "developer", "development", "device", "devil", "devise", "devote", "devoted", "devotion", "diagnose", "diagnosis", "diagram", "dial", "dialogue", "diameter", "diamond", "diary", "dictator",
  "dictionary", "die", "diet", "differ", "difference", "different", "differently", "difficult", "difficulty", "dig", "digest", "digital", "dignity", "dilemma", "dimension", "diminish", "dine", "dinner", "dip", "diplomat",
  "direct", "direction", "directly", "director", "directory", "dirt", "dirty", "disability", "disable", "disadvantage", "disagree", "disagreement", "disappear", "disappoint", "disappointed", "disappointment", "disaster", "disastrous", "disc", "discard",
  "discharge", "discipline", "disclose", "disclosure", "discount", "discourage", "discover", "discovery", "discuss", "discussion", "disease", "disgrace", "disguise", "disgust", "dish", "dishonest", "dislike", "dismiss", "dismissal", "disorder",
  "dispatch", "displace", "display", "disposal", "dispose", "dispute", "disrupt", "disruption", "dissolve", "distance", "distant", "distinction", "distinctive", "distinguish", "distort", "distract", "distraction", "distress", "distribute", "distribution",
  "distributor", "district", "disturb", "disturbance", "dive", "diver", "diverse", "diversity", "divert", "divide", "divine", "division", "divorce", "doc", "doctor", "document", "documentary", "documentation", "dog", "doll",
  "domain", "domestic", "dominant", "dominate", "donation", "donor", "doom", "door", "doorway", "dose", "dot", "double", "doubt", "doubtful", "dove", "down", "downward", "draft", "drag", "drain",
  "drama", "dramatic", "dramatically", "draw", "drawer", "drawing", "dread", "dream", "dress", "drift", "drill", "drink", "drip", "drive", "driver", "driveway", "drop", "drown", "drug", "drum",
  "drunk", "dry", "dual", "duck", "due", "dull", "dumb", "dump", "durable", "duration", "during", "dust", "dusty", "duty", "dynamic", "each", "eager", "eagle", "ear", "early", "earn",
  "earnings", "earth", "earthquake", "ease", "easily", "east", "eastern", "easy", "eat", "echo", "ecological", "ecology", "economic", "economical", "economics", "economist", "economy", "edge", "edit", "edition",
  "editor", "editorial", "educate", "education", "educational", "educator", "effect", "effective", "effectively", "effectiveness", "efficiency", "efficient", "efficiently", "effort", "egg", "ego", "eight", "eighteen", "eighty", "either",
  "elaborate", "elbow", "elder", "elderly", "elect", "election", "electric", "electrical", "electrician", "electricity", "electron", "electronic", "elegant", "element", "elementary", "elephant", "elevator", "eleven", "eligible", "eliminate",
  "elimination", "elite", "else", "elsewhere", "email", "embark", "embarrass", "embarrassed", "embarrassing", "embarrassment", "embassy", "embrace", "emerge", "emergence", "emergency", "emission", "emotion", "emotional", "emotionally", "emperor",
  "emphasis", "emphasize", "empire", "employ", "employee", "employer", "employment", "empower", "empty", "enable", "enact", "enclose", "encounter", "encourage", "encouragement", "end", "endanger", "endeavor", "ending", "endless",
  "endure", "enemy", "energy", "enforce", "enforcement", "engage", "engaged", "engagement", "engine", "engineer", "engineering", "english", "enhance", "enhancement", "enjoy", "enjoyable", "enormous", "enough", "enquire", "enquiry",
  "ensure", "enter", "enterprise", "entertain", "entertainer", "entertainment", "enthusiasm", "enthusiastic", "entire", "entirely", "entitle", "entity", "entrance", "entrepreneur", "entry", "envelope", "environment", "environmental", "envisage", "envy",
  "episode", "equal", "equality", "equally", "equation", "equip", "equipment", "equivalent", "era", "erase", "erect", "error", "rupt", "ruption", "escalate", "escape", "escort", "especially", "essay", "essential",
  "essentially", "establish", "establishment", "estate", "estimate", "estimation", "eternal", "ethical", "ethics", "ethnic", "euro", "evacuate", "evaluate", "evaluation", "eve", "even", "evening", "event", "eventually", "ever",
  "every", "everybody", "everyday", "everyone", "everything", "everywhere", "evidence", "evident", "evidently", "evil", "evolution", "evolve", "exact", "exactly", "exaggerate", "exam", "examination", "examine", "examiner", "example",
  "exceed", "excellent", "except", "exception", "exceptional", "excess", "excessive", "exchange", "excite", "excited", "excitement", "exciting", "exclude", "exclusion", "exclusive", "exclusively", "excuse", "execute", "execution", "executive",
  "exercise", "exert", "exhaust", "exhausted", "exhaustion", "exhibit", "exhibition", "exile", "exist", "existence", "exit", "exotic", "expand", "expansion", "expect", "expectancy", "expectation", "expedition", "expel", "expense",
  "expensive", "experience", "experienced", "experiment", "experimental", "expert", "expertise", "explain", "explanation", "explicit", "explicitly", "explode", "exploit", "exploitation", "exploration", "explore", "explorer", "explosion", "explosive", "export",
  "exporter", "expose", "exposure", "express", "expression", "expressive", "exquisite", "extend", "extension", "extensive", "extent", "exterior", "external", "extra", "extract", "extraction", "extraordinary", "extreme", "extremely", "eye"
];

export const SAMPLE_PARAGRAPHS: string[] = [
  "The quick brown fox jumps over the lazy dog. This pangram contains every single letter in the English alphabet. Typing it repeatedly helps build muscle memory and finger flexibility for beginners and experienced typists alike.",
  "In the world of software engineering, typing speed is often seen as a secondary skill compared to problem-solving ability. However, being able to translate thoughts into code fluidly without looking at the keyboard saves mental energy.",
  "Consistency is the true key to unlocking mastery. Practicing for just fifteen minutes every day is far more beneficial than cramming a three-hour session once a week. Your brain refines connections during sleep, solidifying muscle memory.",
  "Typography is the art and technique of arranging type to make written language legible, readable, and appealing when displayed. The arrangement of type involves selecting typefaces, point sizes, line lengths, line-spacing, and letter-spacing.",
  "A journey of a thousand miles begins with a single step. Focus on your accuracy first, and the speed will naturally follow. When you type with zero errors, your fingers learn the exact locations of the keys and build reliable pathways.",
  "Great design is not just what it looks like and feels like. Design is how it works. A simple, elegant interface that responds instantly to user interaction creates a sense of harmony and focus, allowing the user to enter a state of deep flow.",
  "JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript specification. It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven styles."
];

export const SAMPLE_QUOTES: { text: string; author: string }[] = [
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "It is not query performance that matters, but query simplicity.", author: "Database Sage" }
];
